"""Public H1-A2 reproduction helpers."""

from .science import CONTRIBUTION_ONE, MAIN_RESEARCH_QUESTION, MATERIAL_SPECIFICATION, PUBLIC_RESULT

__all__ = ["CONTRIBUTION_ONE", "MAIN_RESEARCH_QUESTION", "MATERIAL_SPECIFICATION", "PUBLIC_RESULT"]
