#!/usr/bin/env python3
"""Pre-result OR gate for optional new-DLM K4/K8 post-training."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


THRESHOLDS = {
    "native": {"requests": 256, "reconstructed": 252, "strict_sun": 6, "meta_sun": 55},
    "tau800": {"requests": 256, "reconstructed": 252, "strict_sun": 18, "meta_sun": 124},
}
EXPECTED_CURRENT_K4 = {
    "native": {"requests": 256, "reconstructed": 254, "strict_sun": 7, "meta_sun": 57},
    "tau800": {"requests": 256, "reconstructed": 254, "strict_sun": 19, "meta_sun": 126},
}


def read_evaluation(directory, endpoint):
    if not (directory / "_SUCCESS").is_file():
        raise ValueError(f"incomplete evaluation: {directory}")
    report = json.loads((directory / "EVALUATION_FINAL.json").read_text(encoding="utf-8"))
    if (report.get("endpoint") != endpoint
            or report.get("cohort_role") != "fixed_development"
            or report["counts"].get("requests") != 256):
        raise ValueError(f"{directory} is not the frozen {endpoint} development256")
    return report


def metrics(report):
    return {key: int(report["counts"][key])
            for key in ("requests", "reconstructed", "strict_sun", "meta_sun")}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--new-native-eval-dir", type=Path, required=True)
    parser.add_argument("--new-tau-eval-dir", type=Path, required=True)
    parser.add_argument("--current-k4-native-eval-dir", type=Path, required=True)
    parser.add_argument("--current-k4-tau-eval-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    new = {
        "native": read_evaluation(args.new_native_eval_dir, "native"),
        "tau800": read_evaluation(args.new_tau_eval_dir, "tau800"),
    }
    current = {
        "native": read_evaluation(args.current_k4_native_eval_dir, "native"),
        "tau800": read_evaluation(args.current_k4_tau_eval_dir, "tau800"),
    }
    for endpoint in ("native", "tau800"):
        if new[endpoint].get("policy_stage") != "final":
            raise ValueError("new DLM evaluations must use its final base checkpoint")
        for key in ("terminal_protocol", "verification_protocol",
                    "frozen_nu_source_sha256", "official_cache"):
            if new[endpoint][key] != current[endpoint][key]:
                raise ValueError(f"new/current protocol differs at {endpoint}:{key}")
    current_observed = {endpoint: metrics(report) for endpoint, report in current.items()}
    if current_observed != EXPECTED_CURRENT_K4:
        raise ValueError("the preregistered current K4 comparisons changed")
    new_observed = {endpoint: metrics(report) for endpoint, report in new.items()}
    checks = {
        endpoint: {
            key: new_observed[endpoint][key] >= threshold
            for key, threshold in THRESHOLDS[endpoint].items()
        }
        for endpoint in ("native", "tau800")
    }
    endpoint_pass = {
        endpoint: all(values.values()) for endpoint, values in checks.items()
    }
    admitted = any(endpoint_pass.values())
    report = {
        "schema": "periodic_raw_k4_k8_posttrain_admission_v2",
        "admitted": admitted,
        "logical_rule": "native OR tau800",
        "endpoint_pass": endpoint_pass,
        "thresholds_frozen_before_new_results": THRESHOLDS,
        "new_observed": new_observed,
        "current_k4_observed": current_observed,
        "checks": checks,
        "interpretation": (
            "Operational comparability gate authorized by the user; "
            "not a statistical non-inferiority claim."
        ),
        "posttrain_data_rule": (
            "If admitted, collect this new DLM's own K4 then K8 paths. "
            "Do not fit paths generated by the previous DLM."
        ),
    }
    args.output_dir.mkdir(parents=True, exist_ok=False)
    (args.output_dir / "ADMISSION_FINAL.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    (args.output_dir / ("_SUCCESS" if admitted else "_REJECTED")).touch()
    print(json.dumps(report))


if __name__ == "__main__":
    main()
