#!/usr/bin/env python3
"""Pre-result operational gate for optional raw-DLM K4/K8 post-training."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


THRESHOLDS = {
    "requests": 256,
    "reconstructed": 252,
    "strict_sun": 6,
    "meta_sun": 55,
}
EXPECTED_CURRENT_K4 = {
    "requests": 256,
    "reconstructed": 254,
    "strict_sun": 7,
    "meta_sun": 57,
}


def read_evaluation(directory):
    if not (directory / "_SUCCESS").is_file():
        raise ValueError(f"incomplete evaluation: {directory}")
    return json.loads((directory / "EVALUATION_FINAL.json").read_text(encoding="utf-8"))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw-eval-dir", type=Path, required=True)
    parser.add_argument("--current-k4-eval-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    raw = read_evaluation(args.raw_eval_dir)
    current = read_evaluation(args.current_k4_eval_dir)
    for name, report in (("raw", raw), ("current_k4", current)):
        if (report.get("endpoint") != "native"
                or report.get("cohort_role") != "fixed_development"
                or report["counts"].get("requests") != 256):
            raise ValueError(f"{name} is not the frozen native development256")
    if raw.get("policy_stage") != "final":
        raise ValueError("raw DLM evaluation must be its final base checkpoint")
    for key in ("terminal_protocol", "verification_protocol", "frozen_nu_source_sha256",
                "official_cache"):
        if raw[key] != current[key]:
            raise ValueError(f"raw/current evaluation protocol differs: {key}")
    current_observed = {
        key: int(current["counts"][key]) for key in EXPECTED_CURRENT_K4
    }
    if current_observed != EXPECTED_CURRENT_K4:
        raise ValueError("the preregistered current K4 comparison changed")
    raw_observed = {key: int(raw["counts"][key]) for key in THRESHOLDS}
    checks = {
        key: raw_observed[key] >= value for key, value in THRESHOLDS.items()
    }
    admitted = all(checks.values())
    report = {
        "schema": "periodic_raw_k4_k8_posttrain_admission_v1",
        "admitted": admitted,
        "thresholds_frozen_before_raw_results": THRESHOLDS,
        "raw_observed": raw_observed,
        "current_k4_observed": current_observed,
        "checks": checks,
        "interpretation": (
            "Operational comparability gate authorized by the user; "
            "not a statistical non-inferiority claim."
        ),
        "posttrain_data_rule": (
            "If admitted, collect this raw DLM's own K4 then K8 paths. "
            "Do not fit paths generated by the previous DLM."
        ),
    }
    args.output_dir.mkdir(parents=True, exist_ok=False)
    (args.output_dir / "ADMISSION_FINAL.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    (args.output_dir / ("_SUCCESS" if admitted else "_REJECTED")).touch()
    print(json.dumps(report))


if __name__ == "__main__":
    main()
